name: 'CBD - UPLOAD'
description: 'Upload static build files on pull request event'
inputs:
  project-name:
    description:
      "Lower kebab case string (lower-kebab-case-string) allowing to store action's data from multiple
      projects/repositories without collisions in the same bucket."
    required: true
  bucket-name:
    description: 'S3 bucket name to be used to host static websites.'
    required: true
  cloudfront-dist-id:
    description: 'CloudFront distribution id fronting the s3 bucket'
    required: true
  static-build-folder:
    description: 'Relative path from root of the repository to the folder containing all the static files to be deployed'
    required: true
runs:
  using: 'docker'
  image: '../upload.Dockerfile'
  args:
    - ${{ inputs.project-name }}
    - ${{ inputs.bucket-name }}
    - ${{ inputs.cloudfront-dist-id }}
    - ${{ inputs.static-build-folder }}
