on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./upload
        with:
          project-name: some-project-name
          bucket-name: commit-bucket-deploy
          cloudfront-dist-id: E3DDD2REQ5LG3L
          source-dir: notExistingSourceDirectory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
